version: '3.8'

services:
  pgdb:
    image: postgres:15.0-alpine
    container_name: postgres
    restart: on-failure
    ports:
      - "5432:5432"
    env_file:
      - .env/postgresql/.env
    volumes:
      - db_data:/var/lib/postgresql/data/

  nodejs-parcel:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: nodejs-parcel
    restart: always
    volumes:
      - bundles:/app/frontend/bundles

  django:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: django
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env/django/.env
    links:
      - "pgdb:pgdb"
    depends_on:
      - pgdb
      - nodejs-parcel
    volumes:
      - bundles:/app/frontend/bundles
      - media:/app/frontend/media
      - static:/app/frontend/static

volumes:
  bundles: null
  db_data:
    driver: local
    driver_opts:
      type: none
      device: db_data
      o: bind
  media:
    driver: local
    driver_opts:
      type: none
      device: frontend/media
      o: bind
  static:
    driver: local
    driver_opts:
      type: none
      device: frontend/static
      o: bind
