version: '3'

services:
  pgdb:
    image: postgres:15.0-alpine
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env/postgresql/.env
    volumes:
      - db_data:/var/lib/postgresql/data/

  web:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    container_name: django
    command: "
      gunicorn -w 2 -b 0.0.0.0:8000 star_burger.wsgi:application
    "
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env/django/.env
    links:
      - "pgdb:pgdb"
    depends_on:
      - pgdb
    volumes:
      - web_media:/opt/star_burger/media
      - web_static:/opt/star_burger/static

volumes:
  db_data: null
  web_media: null
  web_static: null
