version: '3.8'

services:
  pgdb:
    image: postgres:15.0-alpine
    container_name: postgres
    restart: on-failure
    ports:
      - "5432:5432"
    env_file:
      - .env/postgresql/.env
    volumes:
      - db_data:/var/lib/postgresql/data/

  nodejs-parcel:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    container_name: nodejs-parcel
    restart: always
    volumes:
      - bundles:/app/bundles

  django:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    container_name: django
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env/django/.env
    links:
      - "pgdb:pgdb"
    depends_on:
      - pgdb
      - nodejs-parcel
    volumes:
      - bundles:/app/bundles
      - media:/app/media
      - static:/app/static

volumes:
  bundles: null
  db_data:
    external: false
    driver: local
    driver_opts:
      type: none
      device: ./db_data
      o: bind
  media:
    external: false
    driver: local
    driver_opts:
      type: none
      device: ./media
      o: bind
  static:
    external: false
    driver: local
    driver_opts:
      type: none
      device: ./static
      o: bind