version: '3'

services:
  pgdb:
    image: postgres:15.0-alpine
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env/postgresql/.env
    volumes:
      - db_data:/var/lib/postgresql/data/

  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env/django/.env
    links:
      - "pgdb:pgdb"
    depends_on:
      - pgdb

volumes:
  db_data: null

