# Generated by Django 3.2.15 on 2023-01-05 10:56

import django.core.validators
from django.db import migrations, models


def move_flat_owners_to_owner(apps, schema_editor):
    OrderKit = apps.get_model('foodcartapp', 'OrderKit')
    for order_kit in OrderKit.objects.iterator():
        product = order_kit.product
        count = order_kit.count
        order_kit.price = product.price * count
        order_kit.save()


def rollback(apps, schema_editor):
    OrderKit = apps.get_model('foodcartapp', 'OrderKit')
    for order_kit in OrderKit.objects.iterator():
        order_kit.price = 0


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_auto_20221227_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderkit',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='стоимость'),
            preserve_default=False,
        ),
        migrations.RunPython(move_flat_owners_to_owner, rollback),
    ]
