# Generated by Django 3.2.15 on 2023-01-06 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_data_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, max_length=500, verbose_name='комментарий'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='доставлен'),
        ),
        migrations.AddField(
            model_name='order',
            name='pay',
            field=models.CharField(choices=[('cash', 'Наличными'), ('card', 'Картой'), ('online', 'Онлайн')], db_index=True, default='cash', max_length=15, verbose_name='оплата'),
        ),
        migrations.AddField(
            model_name='order',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='обработан'),
        ),
        migrations.AddField(
            model_name='order',
            name='registered_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='оформлен'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('not processed', 'Необработан'), ('cooking', 'Готовится'), ('on way', 'В пути'), ('delivered', 'Доставлен')], db_index=True, default='not processed', max_length=15, verbose_name='статус'),
        ),
    ]
