# Generated by Django 3.2.15 on 2023-01-07 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_auto_20230106_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodcartapp.restaurant', verbose_name='Готовится в ресторане'),
        ),
        migrations.CreateModel(
            name='OrderKitRestaurants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_to_client', models.PositiveSmallIntegerField(default=0,verbose_name='расстояние до клиента')),
                ('order_kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodcartapp.orderkit', verbose_name='продукт из заказа')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodcartapp.restaurant', verbose_name='может приготовить ресторан')),
            ],
            options={
                'verbose_name': 'ресторан приготовит продукт из заказа',
                'verbose_name_plural': 'рестораны приготовят продукты из заказа',
            },
        ),
        migrations.AddField(
            model_name='orderkit',
            name='restaurants',
            field=models.ManyToManyField(related_name='orders', through='foodcartapp.OrderKitRestaurants', to='foodcartapp.Restaurant', verbose_name='где может приготовится'),
        ),
    ]
