# Generated by Django 3.2.15 on 2023-01-07 11:54

from django.db import migrations
from django.db.models import Q


def add_restaurants_to_order_kit(apps, schema_editor):
    OrderKit = apps.get_model('foodcartapp', 'OrderKit')
    Restaurant = apps.get_model('foodcartapp', 'Restaurant')
    for order_kit in OrderKit.objects.iterator():
        product = order_kit.product
        restaurants = Restaurant.objects.filter(
            Q(menu_items__product=product)
            &
            Q(menu_items__availability=True)
        )
        for restaurant in restaurants:
            order_kit.restaurants.add(restaurant)


def rollback(apps, schema_editor):
    OrderKit = apps.get_model('foodcartapp', 'OrderKit')
    for order_kit in OrderKit.objects.iterator():
        order_kit.restaurants.clear()



class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_auto_20230107_1452'),
    ]

    operations = [
        migrations.RunPython(add_restaurants_to_order_kit, rollback),
    ]
