# Generated by Django 3.2.15 on 2023-01-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_data_orderkit_restaurants'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='lat',
            field=models.DecimalField(decimal_places=6, editable=False, max_digits=8, null=True, verbose_name='широта'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='lon',
            field=models.DecimalField(decimal_places=6, editable=False, max_digits=8, null=True, verbose_name='долгота'),
        ),
    ]
