# Generated by Django 3.2.15 on 2023-01-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_data_lat_lon_restaurants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderkitrestaurants',
            name='distance_to_client',
            field=models.PositiveIntegerField(verbose_name='расстояние до клиента (м)'),
        ),
    ]
