# Generated by Django 3.2.15 on 2023-01-13 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_alter_orderkitrestaurants_distance_to_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRestaurants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_to_client', models.PositiveIntegerField(verbose_name='расстояние до клиента (м)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodcartapp.order', verbose_name='заказ')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodcartapp.restaurant', verbose_name='может приготовить ресторан')),
            ],
            options={
                'verbose_name': 'ресторан приготовит продукт из заказа',
                'verbose_name_plural': 'рестораны приготовят продукты из заказа',
            },
        ),
        migrations.RemoveField(
            model_name='orderkit',
            name='restaurants',
        ),
        migrations.DeleteModel(
            name='OrderKitRestaurants',
        ),
        migrations.AddField(
            model_name='order',
            name='restaurants',
            field=models.ManyToManyField(editable=False, related_name='orders', through='foodcartapp.OrderRestaurants', to='foodcartapp.Restaurant', verbose_name='где может приготовится'),
        ),
    ]
