# Generated by Django 3.2.15 on 2023-01-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_auto_20230114_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1 not processed', 'Необработан'), ('2 cooking', 'Готовится'), ('3 on way', 'В пути'), ('4 delivered', 'Доставлен')], db_index=True, default='1 not processed', max_length=15, verbose_name='статус'),
        ),
    ]
