# Generated by Django 3.2.15 on 2023-01-14 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrestaurants',
            name='availability_all_products',
            field=models.BooleanField(db_index=True, default=False, verbose_name='в продаже все продукты'),
        ),
        migrations.AlterField(
            model_name='orderrestaurants',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verified_restaurants', to='foodcartapp.order', verbose_name='заказ'),
        ),
        migrations.AlterField(
            model_name='orderrestaurants',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verified_orders', to='foodcartapp.restaurant', verbose_name='может приготовить ресторан'),
        ),
    ]
