# Generated by Django 3.2.15 on 2023-01-26 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_auto_20230126_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderkit',
            name='count',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='количество'),
        ),
    ]
