# Generated by Django 3.2.15 on 2023-01-26 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_alter_orderkit_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pay',
            new_name='payment',
        ),
    ]
