# Generated by Django 3.2.15 on 2023-01-28 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0057_rename_restaurant_order_preparing_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_to_client', models.PositiveIntegerField(verbose_name='расстояние до клиента (м)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distance_to_restaurants', to='foodcartapp.order', verbose_name='заказ')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distance_to_clients', to='foodcartapp.restaurant', verbose_name='может приготовить ресторан')),
            ],
            options={
                'verbose_name': 'ресторан приготовит продукт из заказа',
                'verbose_name_plural': 'рестораны приготовят продукты из заказа',
                'ordering': ['distance_to_client'],
            },
        ),
        migrations.DeleteModel(
            name='OrderRestaurants',
        ),
    ]
