# Generated by Django 3.2.15 on 2023-02-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0059_auto_20230213_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('not specified', 'Не указан'), ('cash', 'Наличными'), ('card', 'Картой'), ('online', 'Онлайн')], db_index=True, default='not specified', max_length=15, verbose_name='оплата'),
        ),
    ]
