# Generated by Django 3.2.15 on 2023-02-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0060_alter_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distance',
            name='distance_to_client',
            field=models.PositiveIntegerField(default=0, verbose_name='расстояние до клиента (м)'),
        ),
    ]
