# Generated by Django 3.2.15 on 2023-03-02 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0061_alter_distance_distance_to_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.PositiveIntegerField(default=None, null=True, verbose_name='расстояние доставки (м)')),
            ],
            options={
                'verbose_name': 'ресторан приготовит продукт из заказа',
                'verbose_name_plural': 'рестораны приготовят продукты из заказов',
                'ordering': ['distance'],
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('not specified', 'Не указана'), ('cash', 'Наличными'), ('card', 'Картой'), ('online', 'Онлайн')], db_index=True, default='not specified', max_length=15, verbose_name='оплата'),
        ),
        migrations.AlterField(
            model_name='orderkit',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kits', to='foodcartapp.order', verbose_name='заказ'),
        ),
        migrations.AlterField(
            model_name='orderkit',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kits', to='foodcartapp.product', verbose_name='продукт'),
        ),
        migrations.DeleteModel(
            name='Distance',
        ),
        migrations.AddField(
            model_name='delivery',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='foodcartapp.order', verbose_name='заказ'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='foodcartapp.restaurant', verbose_name='может приготовить ресторан'),
        ),
    ]
